id: https://artemzin.com/static/thecontext/episodes/The.Context.episode.18.part1.mp3
title: "Episode 18, Part 1: Android Everywhere"
description: "In the first part of episode #18 Artur, Hannes und Artem discuss Android tablets, Chromebooks and Android Wear (Wear OS)."
peopleIds: 
  hosts: [Artur, Artem, Hannes]
  guests: []
url: https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_18_Part1.md
discussionUrl: https://github.com/artem-zinnatullin/TheContext-Podcast/issues/92
date: 2018-05-05
duration: 53:49
file: 
  url: https://artemzin.com/static/thecontext/episodes/The.Context.episode.18.part1.mp3
  length: 45465440
