id: https://artemzin.com/static/thecontext/episodes/The.Context.episode.19.part2.mp3
title: "Episode 19, Part 2: Model-View-Intent with Benoît Quenaudon from Square"
description: "In the second part of episode #19 Artur and Hannes continue the discussion with Benoît Quenaudon from Square about Model-View-Intent."
peopleIds: 
  hosts: [Artur, Hannes]
  guests: [BenoitQuenaudon]
url: https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_19_Part2.md
discussionUrl: https://github.com/artem-zinnatullin/TheContext-Podcast/issues/95
date: 2018-06-10
duration: 48:37
file: 
  url: https://artemzin.com/static/thecontext/episodes/The.Context.episode.19.part2.mp3
  length: 41109583
