id: https://github.com/artem-zinnatullin/TheContext-Podcast/releases/download/Episode_3_Part_1/The.Context.episode.3.Part1.mp3
title: "Episode 3, Part 1: RxJava with its core developer David Karnok"
description: In this part of the episode we have talked about RxJava.
peopleIds: 
  hosts: ["Artem"]
  guests: ["DavidKarnok"]
url: https://github.com/artem-zinnatullin/TheContext-Podcast/blob/master/show_notes/Episode_3_part1.md
discussionUrl: https://github.com/artem-zinnatullin/TheContext-Podcast/issues/25
date: 2016-03-09
duration: 44:12
file: 
  url: https://github.com/artem-zinnatullin/TheContext-Podcast/releases/download/Episode_3_Part_1/The.Context.episode.3.Part1.mp3
  length: 63658598


